### ISSUE TITLE
cpu stats only report nanoseconds since start of container

### ISSUE THREAD

**Issue by alexkli** [adobe/node-cgroup-metrics#7]
Currently it reports the raw CPU data which seems to be nanoseconds since the start of the container. Which isn't very useful by itself.

The module would need a way to to measure over some time, get the delta and divide by the time, to get a percentage of CPU usage.

@jdelbick

**Comment by jdelbick** [comment]
The purpose of this module is to get the data at one moment in time. It is not supposed to track metrics over time. This can be done by the user using a sampling library.

Unless we do want to expand this library to run in an interval, collect and aggregate metrics.

**Comment by alexkli** [comment]
Sure, but having clients to do that logic is not quite trivial, i.e. it isn‘t even clear that the value is nanoseconds and that you have to measure the exact time spent between two measurements.

At least there could be a helper function for the calculation. And the „current measurement“ includes a timestamp, so one can calculate the delta.

**Comment by jdelbick** [comment]
Alright that makes sense. I'll add that.

**Comment by jdelbick** [comment]
Closing this issue
