### ISSUE TITLE
remove cpuacct.usage_percpu

### ISSUE THREAD

**Issue by alexkli** [adobe/node-cgroup-metrics#8]
As per #7 we need to adjust how to measure CPU usage. `cpuacct.usage_percpu` reports an array with _all_ CPUs on the host, apparently since over time a cgroup's processes can be run on any CPU of the host.

But it's hard to make any useful use of that information... so I would suggest to remove it for now.

@jdelbick

**Comment by jdelbick** [comment]
Alright I will remove it
